### ISSUE TITLE
Evaluation error

### ISSUE THREAD

**Issue by alien19** [pahn04/PPConv#1]
Hello @pahn04, thanks for your great effort!

I'm trying running the evaluation schema on s3dis dataset, I have through the preprocessing steps, downloaded the pretrained weights provided for the dataset and all is set. It gives an error saying that there is a mismatch between the tensor shape in the checkpoint and the current model 
`size mismatch for module.sa_layers.0.0.att_mlp1.layers.0.weight: copying a param with shape torch.Size([16, 6, 1]) from checkpoint, the shape in current model is torch.Size([4, 16, 1])` and other mismatches till the end it gives
`size mismatch for module.fp_layers.3.1.att_mlp2.layers.1.running_var: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([4]).` like this 
![image](https://user-images.githubusercontent.com/42179967/165289418-cc03123d-af83-47ab-8f15-abadf866365b.png)

also another message appears before the aforementioned
![image](https://user-images.githubusercontent.com/42179967/165289245-4ced5254-388d-4a59-9aeb-8b6da73b29a0.png)

so, if there is any support I'd be thankful.

**Comment by pahn04** [comment]
Hello, @alien19.

Our best model on S3DIS with pvcnn code used Context-Aware Fusion (CAF) module, which is one of the two candidate fusion modules used in PPConv.

We implemented to choose one of them in pvcnn_code/models/utils.py, and the error occurred because the default option was set to choose Importance-Weighted Fusion (IWF) instead of CAF.

We just uploaded a modified version of the code now, and it should work fine.

The only thing that you need to change from the previous version is at the top of pvcnn_code/models/utils.py
uncomment "from modules import Conv_pillar_caf as Conv_module" and comment "from modules import Conv_pillar_iwf as Conv_module"

If you have any other problems, please let me know.

**Comment by alien19** [comment]
Thanks @pahn04 this was really the problem. I have run the test_s3dis bash script and got the .npy result file but I'm wondering about its visualization. Do you use certain code for that or use that part from Pointnet?

**Comment by pahn04** [comment]
I see that you already saved the predictions into a .npy file. As the authors of FPConv paper provided a code for visualization using open3d, we used that one for the figures in the paper.
Please refer to the code at fpconv_code/tools/vis_s3dis.py and after installing open3d in your environment by typing "pip install open3d".

As the error that you initially asked about is now resolved, I'm going to close this issue now. Please open another issue for any other problems you encounter.
