### ISSUE TITLE
Generate only pseudo image

### ISSUE THREAD

**Issue by Shahmad99** [pahn04/PPConv#3]
Hi, can we use the just "projection network" only to generate pseudo image from point cloud? i want to perform some other experiment on pseudo image. But I am confused how to use only the projection network from this code. Thanks

**Comment by pahn04** [comment]
Hello, I appreciate your interest in our project.

The way I understood your question is that you want to use the projection module so that you can transform point cloud into an image-like feature map.

This can be performed using the projection module in the projection branch, which is implemented as part of the projection-based convolutional module in the following code.
https://github.com/pahn04/PPConv/blob/395957b919786bb5b603f37a94ccf9173afce085/pvcnn_code/modules/conv_pillar_caf.py#L89
The output variable proj_x is in the form of B x C x H x W, where B is the batch size and the other dimensions denote the size of pseudo-image feature map.
The projection module (which is called as self.projection) is implemented in the following code.
https://github.com/pahn04/PPConv/blob/395957b919786bb5b603f37a94ccf9173afce085/pvcnn_code/modules/projection.py

For further explanation, you can refer to the section IV. B. 1) in our paper.
